# Generated by Django 6.0.4 on 2026-04-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("letters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="letter",
            name="encrypted_content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="letter",
            name="encrypted_metadata",
            field=models.TextField(blank=True, null=True),
        ),
    ]
