# Generated by Django 6.0.4 on 2026-04-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("letters", "0002_letter_encrypted_content_letter_encrypted_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="letter",
            name="unlock_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
