# Generated by Django 6.0.4 on 2026-04-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("letters", "0003_letter_unlock_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="letter",
            name="burned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="letter",
            name="opened_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="letter",
            name="sealed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
