# Generated by Django 6.0.4 on 2026-04-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("letters", "0004_letter_burned_at_letter_opened_at_letter_sealed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="letter",
            name="encrypted_dek",
            field=models.TextField(blank=True, null=True),
        ),
    ]
