# Generated by Django 6.0.4 on 2026-04-11 20:17

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("letters", "0005_letter_encrypted_dek"),
    ]

    operations = [
        migrations.CreateModel(
            name="LetterImage",
            fields=[
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("file_name", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="encrypted-images/")),
                (
                    "letter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="images", to="letters.letter"
                    ),
                ),
            ],
        ),
    ]
