# Generated by Django 6.0.4 on 2026-04-15 18:13

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("letters", "0006_letterimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="letter",
            name="public_id",
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
