# Generated by Django 6.0.4 on 2026-04-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("letters", "0007_alter_letter_public_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="letter",
            name="notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
