# Generated by Django 6.0.4 on 2026-04-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("letters", "0008_letter_notified_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="letter",
            name="notified_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="letter",
            name="unlock_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
