# Generated by Django 6.0.4 on 2026-04-15 18:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_public_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="kdf_salt",
        ),
    ]
